# Generated by Django 3.1 on 2021-01-03 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='network.post'),
        ),
    ]
